### ISSUE TITLE
[UPDATE] 2.0/Space Age

### ISSUE THREAD

**Issue by L1Z3** [UnlegitSenpaii/FAE_Linux#10] opened 2024-10-23 06:15 UTC
**Layer 8 Handler**
Did you rerun the patcher after updating?

Yes.

**Game Information:**
 - Factorio Version: 2.0.9 (with Space Age DLC)

**Program Output**
Copy Paste the Program or Error Output

<details>
<summary>Output from patcher</summary>

```
[FAE] Initialized Logging.
[FAE] Provided path exits.
[FAE] Patching instructions to JNZ..
[FAE] Patching AchievementGui::AchievementGui with following data:
 pattern:	0x35b48380
 replacement pattern:	0x35b48330
 0 matches for the pattern.
[FAE]  -> FAILED!
[FAE] Patching SteamContext::onUserStatsReceived with following data:
 pattern:	0x35b48380
 replacement pattern:	0x35b486a0
 0 matches for the pattern.
[FAE]  -> FAILED!
[FAE] Patching instructions to JMP from JZ..
[FAE] Patching SteamContext::unlockAchievement with following data:
 pattern:	0x35b48380
 replacement pattern:	0x35b48330
 1 matches for the pattern.
[FAE]  -> SUCCESS!
[FAE] Patching SteamContext::setStat with following data:
 pattern:	0x35b486a0
 replacement pattern:	0x35b4b190
 1 matches for the pattern.
[FAE]  -> SUCCESS!
[FAE] Patching instructions to JMP from JNZ..
[FAE] Patching AchievementGui::allowed with following data:
 pattern:	0x35b486a0
 replacement pattern:	0x35b4b170
 0 matches for the pattern.
[FAE]  -> FAILED!
[FAE] Patching instructions to CMOVZ from CMOVNZ..
[FAE] Patching PlayerData::PlayerData with following data:
 pattern:	0x35b486a0
 replacement pattern:	0x35b4b190
 0 matches for the pattern.
[FAE]  -> FAILED!
[FAE] Marking Factorio as an executable..
```

</details>

**Additional context**
Would be great if you already have the new memory patterns :)

The Windows version has already been updated to 2.0.7 (and 2.0.8/2.0.9 seem to be minor updates). If I get some free time I'd be happy to make some attempts at finding the new memory patterns (although my experience with reverse engineering is pretty minimal.)

**Comment by UnlegitSenpaii** [comment] 2024-10-24 19:25
fixed with [commit](https://github.com/UnlegitSenpaii/FAE_Linux/commit/650db40a5acc5518d1e137e05bb5bd1003dee776)
feedback would be great, as im currently testing it myself.

**Comment by L1Z3** [comment] 2024-10-25 00:27
Seems to work! I was able to get a Steam achievement with mods installed. I did get an error about local achievement data getting corrupted though, and when I disabled the patch, my modded achievement data seemed to be reset.

**Comment by UnlegitSenpaii** [comment] 2024-10-25 15:32
yes thats because your modded achievements are saved to a different save file.
achievement-modded.dat for modded archivements and achievement.dat for normal ones.
expected behaviour.

**Closed** 2024-10-25 18:11 UTC
Labels: gameupdate
